
# NPC CONFIG 
# ALL NPC TYPES 
# 
#	

NPC_FLAG_NONE = 0
NPC_FLAG_QUESTGIVER = 1
NPC_FLAG_QUESTRESPONDER = 2
NPC_FLAG_VENDOR = 4
NPC_FLAG_TRAINER = 8
NPC_FLAG_GUARD = 16
NPC_FLAG_BANKER = 32
NPC_FLAG_AUCTIONEER = 64
NPC_FLAG_CONSORTIA = 128
NPC_FLAG_CONSORTIA_LEVELUP = 256
NPC_FLAG_SYS = 512

#NPC_FLAG_SYS
NPC_FLAG_SYS_NONE    = 0
NPC_FLAG_SYS_TRANMIT = 1
NPC_FLAG_SYS_CREDIT_EXCHANGE = 2
NPC_FLAG_SYS_GRANT_OFFICAL   = 4
NPC_FLAG_SYS_OFFICAL_SALARY  = 8
NPC_FLAG_SYS_ALTAR = 16

NPC_FLAG_GuildQuest = 32 



ITEM_TYPE_HOT = 0
ITEM_TYPE_RECOVER = 1
ITEM_TYPE_GROCERY = 2
ITEM_TYPE_WEAPON = 3
ITEM_TYPE_HELMET = 4
ITEM_TYPE_BREAST = 5
ITEM_TYPE_BELT = 6
ITEM_TYPE_TIBIA = 7
ITEM_TYPE_SHIELD = 8
ITEM_TYPE_GLOVE = 9
ITEM_TYPE_SHOES = 10
ITEM_TYPE_SKILLBOOK1 = 11
ITEM_TYPE_SKILLBOOK2 = 12
ITEM_TYPE_SKILLBOOK3 = 13
ITEM_TYPE_SKILLBOOK4 = 14
ITEM_TYPE_HUFU = 15
ITEM_TYPE_RING = 16
ITEM_TYPE_HUZHOU = 17
ITEM_TYPE_BAOSHI = 18

TYPE_OBLATION_CREATE_LEVELUP = 0
TYPE_OBLATION_DELETE = 1